name: SSH Ubuntu 22.04

on: [workflow_dispatch]

jobs:
  ssh:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup SSH and ngrok
        run: |
          sudo apt update
          sudo apt install -y openssh-server wget unzip

          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PermitEmptyPasswords no" | sudo tee -a /etc/ssh/sshd_config
          echo "root:123456" | sudo chpasswd

          sudo service ssh restart

          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok

          ./ngrok authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"
          ./ngrok tcp 22 > /dev/null &
          sleep 10

          curl -s http://127.0.0.1:4040/api/tunnels | tee tunnels.json
