name: SSH Ubuntu 22.04

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Start SSH via ngrok
        run: |
          sudo apt update
          sudo apt install -y openssh-server wget unzip
          sudo service ssh start

          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok

          echo "${{ secrets.NGROK_AUTH_TOKEN }}" > ngrok_token
          ./ngrok authtoken $(cat ngrok_token)
          ./ngrok tcp 22 > ngrok.log &
          sleep 10
          curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
          echo "Ngrok Tunnel Info:"
          cat tunnels.json
